name = "day_2"
description = "Advent 2024 Day 2"
version = "0.1.0-dev"

authors = ["Bob Plested"]
maintainers = ["Bob Plested <agar29@yahoo.com>"]
maintainers-logins = ["plestedr"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["day_2"]

